name: Deploy
on:
  push:
    branches: [ "master"]


jobs:
  Down:
    runs-on: self-hosted
    steps:
      - name: cd into repo
        uses: actions/checkout@v2
      - name: Down service
        run: make down
  Clean:
    needs: Down
    runs-on: self-hosted
    steps:
      - name: cd into repo
        uses: actions/checkout@v2
      - name: Clean images
        run: make clean
  Build:
    needs: Clean
    runs-on: self-hosted
    steps:
      - name: cd into repo
        uses: actions/checkout@v2
      - name: Build images
        run: make build
  Up:
    needs: Build
    runs-on: self-hosted
    steps:
      - name: cd into repo
        uses: actions/checkout@v2
      - name: Up service
        run: make init
